// FSM.h
// Andrew Lynch
// February 8, 2018

// [YOUR NAMES HERE]
// [DATES YOU MADE CHANGES]

// [WHAT YOUR PROJECT DOES]

// [USER NOTES - DESCRIPTION OF FUNCTION]
// [INPUTS DESCRIPTION]
// [OUTPUTS DESCRIPTION, CURRENTLY NONE]
void runFSM(int * errorCodeArray);
